name: Build examples
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install Arduino CLI
      uses: arduino/setup-arduino-cli@v1
      board_manager:
        additional_urls:
          - https://arduino.esp8266.com/stable/package_esp8266com_index.json
            arduino-cli compile --fqbn arduino:samd:mkr1000 MyFirstSketch
